#!/usr/bin/env python3
"""DRAFT timing preview for the talk show. NOT a deliverable.

Writes preview/promo.yaml (gitignored): the real promo.yaml with every shot whose clip is not in the footage manifest
(or whose file is missing) swapped for a clearly labelled card "PLACEHOLDER: footage not yet captured: <clip> (beat N)".
Everything else (VO, host layers, real clips, chat, credits) is identical and shares build/ (host layers are reused
from the cache). Output: preview/out/ -> copied to $PREVIEW_DIR (default /workspace/promo-reel-evals) as
talkshow-preview.mp4 + talkshow-preview-contact.png.

    nice -n 10 python projects/commission-ai-talkshow/make_preview.py [--name=talkshow-preview-v2]
"""
import os
import shutil
import subprocess
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, REPO)


def main():
    from promo import footage as FT
    from promo.spec import load_spec
    spec = load_spec(os.path.join(HERE, "promo.yaml"))
    have = {}
    for s in spec.shots:
        src = (s.cfg.get("screen") or {}).get("source")
        if src:
            try:
                p = spec.footage_path(src)
                have[src] = bool(p and os.path.exists(p))
            except Exception:  # noqa: BLE001
                have[src] = False
    head, body = open(os.path.join(HERE, "promo.yaml")).read().split("\nproject:", 1)
    raw = yaml.safe_load("project:" + body)
    missing = []
    for s in raw["shots"]:
        src = (s.get("screen") or {}).get("source")
        if src and not have.get(src):
            missing.append((s["id"], src, s.get("beat")))
            s["screen"] = {"placeholder": f"PLACEHOLDER (draft preview only)\nfootage not yet captured: {src}\nbeat {s.get('beat')}, shot {s['id']}"}
            s.pop("text_check", None)
    raw["paths"] = {"build": "../build", "out": "out"}
    raw["assets"] = "assets.yaml"
    am = yaml.safe_load(open(os.path.join(HERE, "assets.yaml")))
    for a in am["assets"]:                     # same manifest, relative paths re-rooted at the project dir
        p = a.get("path", "")
        if p and not p.startswith(("/", "$")):
            a["path"] = "../" + p
    raw["output"]["name"] = "commission-ai-talkshow-PREVIEW"
    os.makedirs(os.path.join(HERE, "preview"), exist_ok=True)
    with open(os.path.join(HERE, "preview", "assets.yaml"), "w") as f:
        yaml.safe_dump(am, f, sort_keys=False, width=160)
    out = os.path.join(HERE, "preview", "promo.yaml")
    with open(out, "w") as f:
        f.write("# DRAFT PREVIEW SPEC (generated by make_preview.py, gitignored). Placeholder cards for missing footage: "
                "NOT a deliverable.\n" + yaml.safe_dump(raw, sort_keys=False, allow_unicode=True, width=160))
    print("placeholders:", ", ".join(f"{i}={c} (beat {b})" for i, c, b in missing) or "none")
    py = sys.executable
    subprocess.check_call(["nice", "-n", "10", py, "-m", "promo", "-p", out, "build"], cwd=REPO)
    ps = load_spec(out)
    mp4 = ps.output_path("")
    subprocess.check_call(["nice", "-n", "10", py, "-m", "promo", "-p", out, "contact"], cwd=REPO)
    from promo import contact
    png, _ = contact.contact_paths(ps)
    dst = os.environ.get("PREVIEW_DIR", "/workspace/promo-reel-evals")
    os.makedirs(dst, exist_ok=True)
    name = next((a.split("=", 1)[1] for a in sys.argv[1:] if a.startswith("--name=")), "talkshow-preview")
    shutil.copy2(mp4, os.path.join(dst, f"{name}.mp4"))
    shutil.copy2(png, os.path.join(dst, f"{name}-contact.png"))
    print("preview:", os.path.join(dst, f"{name}.mp4"))
    print("contact:", os.path.join(dst, f"{name}-contact.png"))


if __name__ == "__main__":
    main()
