"""Footage manifest (projects/<name>/footage/manifest.yaml): the authoritative record of every raw capture.

Raw footage never goes in git (no LFS): it stays on the box, and the manifest says where it is and exactly which bytes
(sha256) the spec was built against. Shots reference clips by manifest id (`source: shot-10-v1080`); an id missing from
the manifest is an error (no directory fallback).

Per clip: id, shots, path (ABSOLUTE, ${VAR:-default} ok), sha256, app_commit, capture, framing, resolution, dpr, fps,
captured_at, notes, demo, generated ({provider, prompt, ...}: AI-generated non-UI plate, see promo/genvideo.py).   `promo footage add|verify|list`; `promo build|shot|check` gate on verify.
sha256 results are cached in build/footage-hashes.json keyed by (path, size, mtime_ns), so multi-GB clips are hashed once.
"""
from __future__ import annotations

import datetime
import hashlib
import json
import os
import subprocess

import yaml

from .spec import SpecError, expand_env

FIELDS = ["id", "shots", "path", "sha256", "app_commit", "capture", "framing", "resolution", "dpr", "fps", "captured_at", "notes", "demo", "generated"]
SOURCE_KEYS = {"source", "still", "board", "node"}      # spec keys (anywhere inside a shot / plate) whose string value is a clip id
RECAPTURE = "re-capture or update the manifest via `promo footage add`"
MD_BEGIN, MD_END = "<!-- promo:footage-table BEGIN (generated by `promo footage add`; edit manifest.yaml, not this table) -->", "<!-- promo:footage-table END -->"
HEADER = ("# Footage manifest (authoritative, machine-readable). Raw media is NOT in git: it lives at `path` on the box.\n"
          "# Maintained with `promo footage add`; see manifest.md for human notes.\n")


class FootageError(SpecError):
    pass


def manifest_path(spec):
    return spec.resolve(spec.raw.get("footage", "footage/manifest.yaml"))


def load_raw(path):
    """Manifest as written (no env expansion) -> list of clip dicts. Missing file = empty."""
    if not os.path.exists(path):
        return []
    with open(path) as f:
        d = yaml.safe_load(f) or {}
    return list(d.get("clips", d) if isinstance(d, dict) else d)


def load(spec):
    """{id: clip} with env-expanded absolute `path`. Raises FootageError if the manifest is missing/malformed."""
    cached = getattr(spec, "_footage", None)
    if cached is not None:
        return cached
    p = manifest_path(spec)
    if not os.path.exists(p):
        raise FootageError(f"footage manifest not found: {p} (create it with `promo footage add`)")
    out = {}
    for c in expand_env(load_raw(p)):
        if "id" not in c:
            raise FootageError(f"clip without id in {p}: {c}")
        if c["id"] in out:
            raise FootageError(f"duplicate clip id {c['id']} in {p}")
        out[c["id"]] = c
    spec._footage = out
    return out


def clip_path(spec, cid):
    """Absolute path of clip `cid` (error if the id is not in the manifest)."""
    man = load(spec)
    if cid not in man:
        raise FootageError(f"clip {cid!r} is not in the footage manifest {manifest_path(spec)} "
                           f"(known: {', '.join(sorted(man)) or 'none'}); {RECAPTURE}")
    return man[cid]["path"]


def _walk(obj, key, found, shot_id):
    if isinstance(obj, dict):
        for k, v in obj.items():
            _walk(v, k, found, shot_id)
    elif isinstance(obj, list):
        for v in obj:
            _walk(v, key, found, shot_id)
    elif isinstance(obj, str) and (key in SOURCE_KEYS or (key == "plate" and "/" not in obj and not os.path.splitext(obj)[1])):
        found.setdefault(obj, [])
        if shot_id not in found[obj]:
            found[obj].append(shot_id)


def referenced(spec, shot_ids=None):
    """{clip id: [shot ids using it]} from every source/still/board/node key in shots and plates."""
    found = {}
    for s in spec.shots:
        if shot_ids is None or s.id in shot_ids:
            _walk(s.cfg, None, found, s.id)
    if shot_ids is None:
        for name, p in (spec.raw.get("plates") or {}).items():
            _walk(p, None, found, f"plate:{name}")
    return found


# ---------------------------------------------------------------- hashing (cached)
def _cache_file(spec):
    return os.path.join(spec.build, "footage-hashes.json")


def sha256_cached(spec, path, cache=None):
    """sha256 of `path`, reusing build/footage-hashes.json when (size, mtime_ns) match."""
    cf = _cache_file(spec)
    cache = cache if cache is not None else (json.load(open(cf)) if os.path.exists(cf) else {})
    st = os.stat(path)
    e = cache.get(path)
    if e and e["size"] == st.st_size and e["mtime_ns"] == st.st_mtime_ns:
        return e["sha256"]
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            b = f.read(1 << 22)
            if not b:
                break
            h.update(b)
    cache[path] = dict(size=st.st_size, mtime_ns=st.st_mtime_ns, sha256=h.hexdigest())
    os.makedirs(spec.build, exist_ok=True)
    with open(cf, "w") as f:
        json.dump(cache, f, indent=1)
    return h.hexdigest()


def verify(spec, shot_ids=None):
    """Check every referenced clip exists and matches its sha256. Returns a list of per-clip result dicts."""
    man = load(spec) if os.path.exists(manifest_path(spec)) else {}
    results = []
    for cid, shots in sorted(referenced(spec, shot_ids).items()):
        r = dict(id=cid, shots=shots, path=None, exists=False, expected=None, actual=None, ok=False, error=None)
        c = man.get(cid)
        if c is None:
            r["error"] = f"clip {cid!r} used by shots {', '.join(shots)} is not in the footage manifest; {RECAPTURE}"
        else:
            r["path"], r["expected"] = c["path"], c.get("sha256")
            if not os.path.exists(c["path"]):
                r["error"] = f"clip {cid!r} (shots {', '.join(shots)}): file not found: {c['path']}; {RECAPTURE}"
            else:
                r["exists"] = True
                if not r["expected"] or len(str(r["expected"])) != 64:
                    r["error"] = f"clip {cid!r} (shots {', '.join(shots)}): manifest has no valid sha256; {RECAPTURE}"
                else:
                    r["actual"] = sha256_cached(spec, c["path"])
                    r["ok"] = r["actual"] == r["expected"]
                    if not r["ok"]:
                        r["error"] = (f"clip {cid!r} (shots {', '.join(shots)}): sha256 mismatch: expected {r['expected']}, "
                                      f"actual {r['actual']} ({c['path']}); {RECAPTURE}")
        results.append(r)
    return results


def gate(spec, shot_ids=None):
    """Raise FootageError listing every bad clip (used by build / shot / check)."""
    bad = [r["error"] for r in verify(spec, shot_ids) if not r["ok"]]
    if bad:
        raise FootageError("footage gate failed:\n  - " + "\n  - ".join(bad))


def verified_sha(spec, cid):
    """sha256 of a clip for stamp digests (hash cached by size+mtime)."""
    return sha256_cached(spec, clip_path(spec, cid))


# ---------------------------------------------------------------- QA helpers
def max_magnification(shot, screen_frac=1.0):
    """Largest push-in on the shot's cameras: 1 / smallest box width (fraction of source width). None if no camera keys.
    A livestream screen cam `screen.cam: [cx, cy, w]` shown on a screen `screen_frac` of the frame wide counts as
    screen_frac / w (e.g. w 1/3 on a 1440-px screen = 2.25x)."""
    ws = []
    sc = shot.cfg.get("screen")
    if isinstance(sc, dict) and isinstance(sc.get("cam"), (list, tuple)) and len(sc["cam"]) == 3 and sc.get("source"):
        ws.append(float(sc["cam"][2]) / screen_frac)

    def keys(v):
        if isinstance(v, list) and v and all(isinstance(k, list) and len(k) >= 4 for k in v):
            ws.extend(k[3] for k in v)

    cfg = shot.cfg
    for name in ("cam", "camA", "camB"):
        keys(cfg.get(name))
    for s in cfg.get("segs") or []:
        keys(s.get("cam"))
    return 1 / min(ws) if ws else None


def qa_findings(spec, mag_limit=1.5):
    """(dpr_warnings, demo_clips): soft-upscale risk (dpr < 2 with magnification > limit) and demo-mode footage in use."""
    man = load(spec)
    dpr, demo = [], []
    for cid, shots in referenced(spec).items():
        c = man.get(cid)
        if c and c.get("demo"):
            demo.append(cid)
    lsc = spec.raw.get("livestream") or {}
    frac = float((lsc.get("screen") or {}).get("w", 1440)) / 1920 if lsc else 1.0
    for s in spec.shots:
        mag = max_magnification(s, frac)
        if not mag or mag <= mag_limit:
            continue
        for cid in {c for c, ss in referenced(spec, {s.id}).items()}:
            c = man.get(cid)
            if c and (c.get("dpr") or 0) < 2 and str(c.get("dpr")) != "unknown":
                dpr.append(f"shot {s.id}: {mag:.1f}x push-in on {cid} (dpr {c.get('dpr')}, {c.get('resolution')}): soft upscale at {spec.OW}x{spec.OH}")
    return dpr, sorted(demo)


# ---------------------------------------------------------------- add / list / md table
def probe_media(path):
    """(resolution 'WxH', fps or None for stills)."""
    o = subprocess.check_output(["ffprobe", "-v", "error", "-select_streams", "v:0", "-show_entries", "stream=width,height,r_frame_rate,codec_name,nb_frames",
                                 "-of", "json", path]).decode()
    s = json.loads(o)["streams"][0]
    n, d = s["r_frame_rate"].split("/")
    still = path.lower().endswith((".png", ".jpg", ".jpeg", ".webp"))
    return f"{s['width']}x{s['height']}", (None if still else round(float(n) / float(d), 3))


def render_md_table(clips):
    rows = ["| id | shots | resolution | dpr | fps | app commit | captured at | demo | capture |", "|---|---|---|---|---|---|---|---|---|"]
    for c in clips:
        rows.append("| {id} | {shots} | {resolution} | {dpr} | {fps} | `{commit}` | {at} | {demo} | {capture} |".format(
            id=c.get("id"), shots=" ".join(map(str, c.get("shots") or [])), resolution=c.get("resolution", "?"), dpr=c.get("dpr", "?"),
            fps=c.get("fps") or "-", commit=str(c.get("app_commit", "unknown"))[:8], at=c.get("captured_at", "unknown"),
            demo="yes" if c.get("demo") else "no", capture=str(c.get("capture", "unknown")).replace("|", "\\|")))
    return "\n".join(rows)


def sync_md(spec, clips=None):
    """Rewrite the generated table region of manifest.md (appends it if the markers are absent)."""
    mp = os.path.join(os.path.dirname(manifest_path(spec)), "manifest.md")
    clips = clips if clips is not None else load_raw(manifest_path(spec))
    region = f"{MD_BEGIN}\n{render_md_table(clips)}\n{MD_END}\n"
    txt = open(mp).read() if os.path.exists(mp) else f"# Footage notes\n\n"
    if MD_BEGIN in txt and MD_END in txt:
        a, b = txt.index(MD_BEGIN), txt.index(MD_END) + len(MD_END)
        txt = txt[:a] + region.rstrip("\n") + txt[b:]
    else:
        txt = txt.rstrip("\n") + "\n\n## Clips\n\n" + region
    with open(mp, "w") as f:
        f.write(txt)
    return mp


def save(spec, clips):
    p = manifest_path(spec)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    ordered = [{k: c[k] for k in FIELDS if k in c} | {k: v for k, v in c.items() if k not in FIELDS} for c in clips]
    with open(p, "w") as f:
        f.write(HEADER)
        yaml.safe_dump({"clips": ordered}, f, sort_keys=False, allow_unicode=True, width=1000)
    spec._footage = None


def add(spec, path, cid, shots=(), commit="unknown", capture="unknown", framing="unknown", dpr=None, notes="", demo=False,
        captured_at=None, resolution=None, fps=None, generated=None):
    """Append/update a clip: computes sha256, probes resolution/fps, writes manifest.yaml and refreshes the manifest.md table."""
    path = os.path.abspath(os.path.expanduser(path)) if not str(path).startswith("$") else path
    real = expand_env(path)
    if not os.path.exists(real):
        raise FootageError(f"file not found: {real}")
    res, pfps = probe_media(real)
    if captured_at is None:
        captured_at = datetime.datetime.fromtimestamp(os.path.getmtime(real), datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    entry = dict(id=cid, shots=[str(s) for s in shots], path=path, sha256=sha256_cached(spec, real), app_commit=commit, capture=capture,
                 framing=framing, resolution=resolution or res, dpr=dpr if dpr is not None else "unknown", fps=fps if fps is not None else pfps,
                 captured_at=captured_at, notes=notes, demo=bool(demo))
    if generated:
        entry["generated"] = generated           # AI-generated non-UI plate (promo gen); promo check gates where it may be used
    clips = load_raw(manifest_path(spec))
    for i, c in enumerate(clips):
        if c.get("id") == cid:
            clips[i] = entry
            break
    else:
        clips.append(entry)
    save(spec, clips)
    sync_md(spec, clips)
    return entry
